train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [960, 960]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72
        ops: []  # no augmentation ops

  collate_fn:
    type: BatchImageCollateFunction
    base_size: 960
    base_size_repeat: 3
    stop_epoch: 72

  shuffle: True
  total_batch_size: 8
  num_workers: 8

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [960, 960]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 20
  num_workers: 8
