__include__: [
  '../../../dataset/stage_2.yml',
  '../../../runtime.yml',
  '../../include/dataloader_960.yml',
  '../../include/optimizer.yml',
  '../../include/dfine_hgnetv2_960.yml',
]

output_dir: ./output/finetune_stage_2_dfine_l.yml


DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True
  pretrained: False

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000000390625
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0000078125
  betas: [0.9, 0.999]
  weight_decay: 0.000125


epochs: 80 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 74
  collate_fn:
    stop_epoch: 74
    ema_restart_decay: 0.9999
    base_size_repeat: 6

ema:
  warmups: 0

lr_warmup_scheduler:
  warmup_duration: 0

